packages:
  - "apps/admin"
  - "apps/admin-api"
  - "apps/api"
  - "apps/web-app"
  - "apps/web-landing"
  - "packages/**"
catalogs:
  repo-typescript:
    typescript: 5.7.3
  repo-eslint:
    eslint: 9.36.0
    "@eslint/js": 9.36.0
    "@typescript-eslint/eslint-plugin": 8.44.1
    "@typescript-eslint/parser": 8.44.1
    typescript-eslint: 8.44.1
  repo-node-20-types:
    "@types/node": 20.19.16
  repo-node-22-types:
    "@types/node": 22.18.6
  exchange-workers:
    wrangler: 4.40.2
    vitest: 3.2.4
    hono: 4.9.9
    "@cloudflare/vitest-pool-workers": 0.9.7
  repo-nextjs:
    next: 15.4.8
    eslint-config-next: 15.4.8
    "@next/third-parties": 15.4.8
    "@next/bundle-analyzer": 15.4.8
    "@next/eslint-plugin-next": 15.4.8
  repo-react:
    react: 19.2.1
    "react-dom": 19.2.1
    "@types/react": 19.2.7 # major and minor versions should match the react version, patch version can be different
    "@types/react-dom": 19.2.3 # major and minor versions should match the react-dom version, patch version can be different
