import { Header } from '@/components/layout/Header';
import type { Metadata } from 'next';
import ThemeProviderClient from '../components/ThemeProviderClient';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProviderClient>
          <div className="min-h-screen flex flex-col bg-background">
            <Header />

            {children}
          </div>
        </ThemeProviderClient>
      </body>
    </html>
  );
}
